ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'CODE_DECOMP_TREE_CHECKED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'CODE_DECOMP_NODE_HINT_VIEWED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'CODE_DECOMP_NODE_REVEALED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'CODE_DECOMP_STAGE_ADVANCED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'CODE_DECOMP_MATCH_CHECKED';
