-- Prompting-course logger (Phase 2): new ActivityAction values. Additive only.
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'SLIDE_ENTERED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'SLIDE_EXITED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'ATTEMPT_STARTED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'PREDICTION_COMMITTED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'REFERENCE_REVEALED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'GAP_NOTED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'BELIEF_COMMITTED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'BELIEF_REVISED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'MCQ_ANSWERED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'RATIONALE_SUBMITTED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'SELF_CHECK_SUBMITTED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'RESULTS_RECORDED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'CRITERION_SELF_SCORED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'REFLECTION_SUBMITTED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'CONFIDENCE_RATED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'IDLE_STARTED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'IDLE_ENDED';
