import JSZip from 'jszip';

export interface ExportProgress {
  stage: 'fetching' | 'downloading' | 'zipping' | 'done';
  /** 0–100 */
  percent: number;
  detail: string;
}

const README = `GALS Session Export — README
============================

This folder contains all data recorded during one student learning session
on the GALS (Guided Adaptive Learning System) platform.

Generated by: GALS Teacher Dashboard — Export Data
Schema version: 2.0

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FOLDER CONTENTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

session_data.json
  Main data file containing all session events, biometrics, interactions,
  chat messages, and replay metadata in a single structured JSON document.
  The screenshotDataUrl field has been removed from each replay snapshot and
  replaced with a screenshotFile path pointing into screen_recording/ below,
  so the JSON stays a manageable size.

recordings/
  Webcam video files, one per recording segment.
  - recording_0.webm, recording_1.webm, ...
  - Format: WebM (VP8/VP9), no audio, 640x480 @ 15 fps
  - Open with VLC, Chrome, Firefox, or any modern video player.
  - Each segment starts when the student opens a course and ends when they
    leave or the session is paused. Long sessions may produce multiple files.

screen_recording/
  Pixel-accurate screenshots of the student's browser as individual JPEG frames.

  frame_0000.jpg, frame_0001.jpg, ...
    - Format: JPEG, same resolution as the student's browser viewport.
    - Captured at: 1 frame per second (periodic) plus extra frames on
      page navigation, tab visibility change, and session start/end.
    - Total frame count depends on session length and navigation activity.
    - Each frame corresponds to the screenshotFile field in the matching
      replay.snapshots entry in session_data.json.

  To convert frames into a video using ffmpeg (free, offline):
    Real-time (1 fps):  ffmpeg -framerate 1 -i frame_%04d.jpg -c:v libx264 screen_recording.mp4
    5x timelapse:       ffmpeg -framerate 5 -i frame_%04d.jpg -c:v libx264 screen_recording.mp4

dom_snapshots/
  Full HTML of the student's browser at each captured moment.

  snapshot_0000.html, snapshot_0001.html, ...
    - One file per replay snapshot, in chronological order.
    - Open directly in a browser to see exactly what the student saw.
    - Corresponds to the htmlFile field in replay.snapshots in session_data.json.
    - Render in an iframe for interactive session replay; pair with the
      matching frame_NNNN.jpg for a pixel-accurate side-by-side view.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RECORDING TECHNICAL DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Webcam recording
  Capture rate : 15 fps
  Resolution   : 640 x 480 pixels
  Audio        : not recorded
  Storage      : uploaded to MinIO object storage as WebM segments
  Trigger      : starts automatically when student opens a course
                 (requires recording consent and course recording enabled)

Screen / pixel recording
  Capture rate : 1 frame per second (periodic), plus event-triggered frames:
                   - session start (initial)
                   - page/route navigation
                   - tab hidden / window minimised
                   - session end / page close
  Method       : getDisplayMedia() screen capture stream, sampled via canvas
  Format       : JPEG screenshots embedded in DOM snapshot records
  Storage      : stored in the database alongside the DOM snapshot HTML

DOM replay snapshots
  Capture rate : 1 snapshot per second (periodic), same triggers as above
  Content      : full serialised HTML of the student's page at that moment
                 (canvas pixels inlined as base64, external resources
                 replaced with data-URIs where possible)
  Usage        : render in an iframe for a live DOM replay; the pixel
                 screenshot is the fallback thumbnail shown alongside it

Facial emotion analysis (OpenFace 3)
  Capture rate : ~5 fps (sampled from the webcam recording)
  Model        : OpenFace 3 (action unit + emotion classification)
  Output       : emotionFrames and actionUnits in session_data.json

Eye-gaze tracking (WebGazer)
  Capture rate : variable, typically 10–30 samples per second
  Method       : browser-based webcam gaze estimation (no eye-tracking HW)
  Coordinate   : viewport pixels (top-left origin)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SESSION DATA JSON — SECTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

_meta
  Export metadata.
  Fields: exportedAt, schemaVersion, platform, sessionId,
          studentName, courseName, sessionStartedAt.

session
  Core session record.
  Fields: id, startedAt, endedAt, durationSecs, courseId, courseName,
          ipAddress, userAgent.

student
  Student identity.
  Fields: id, name, email.

summary
  AI-generated session summary (if available).
  Produced automatically at session end by the GALS summarisation pipeline.

biometrics.emotionFrames
  Per-frame facial emotion probabilities from OpenFace 3, sampled at ~5 fps.
  Fields:
    frameWallMs      — Unix timestamp in milliseconds (use for video alignment)
    frameIndex       — sequential frame number
    faceDetected     — boolean; false means no face visible in this frame
    pHappiness, pSadness, pSurprise, pFear,
    pAnger, pDisgust, pContempt, pNeutral
                     — probability (0.0–1.0) for each emotion
    dominantEmotion  — name of the highest-probability emotion
    dominantProbability — its probability value
    headPoseYaw      — head rotation left/right in degrees
    headPosePitch    — head rotation up/down in degrees
    headPoseRoll     — head tilt in degrees

biometrics.actionUnits
  Facial Action Unit intensities from py-feat, one row per webcam frame.
  Action Units (AUs) map to specific facial muscle movements defined by
  the Facial Action Coding System (FACS).
  Fields: frameIndex, wallTime (ISO), faceConf (face detection confidence),
          au01 (inner brow raise), au02 (outer brow raise),
          au04 (brow lowerer), au05 (upper lid raiser),
          au06 (cheek raiser), au07 (lid tightener),
          au09 (nose wrinkler), au10 (upper lip raiser),
          au12 (lip corner puller = smile), au14 (dimpler),
          au15 (lip corner depressor), au17 (chin raiser),
          au20 (lip stretcher), au23 (lip tightener),
          au24 (lip pressor), au25 (lips part),
          au26 (jaw drop), au28 (lip suck).

biometrics.gaze
  Eye-gaze coordinates from WebGazer (browser-based, no hardware needed).
  Fields: timestamp (ISO), gazeX (pixels from left), gazeY (pixels from top),
          confidence (0.0–1.0), pageUrl.
  Note: gaze coordinates are in viewport pixels. To map to a specific UI
  region, compare with the viewport size in interactions.viewport.

biometrics.pupil
  Pupil diameter estimates derived from the webcam stream.
  Fields: timestamp (ISO), pupilDiameter (pixels in webcam image space).

interactions.clicks
  Mouse click events.
  Fields: timestamp, x, y (viewport pixels), pageUrl,
          elementSelector (CSS selector of clicked element),
          elementText (visible text of the element, if any).

interactions.scrolls
  Page scroll events.
  Fields: timestamp, scrollY (pixels from top of page),
          scrollPercent (0–100), pageUrl.

interactions.keystrokes
  Aggregated typing activity — keystroke counts and speed, NOT raw keys
  (raw keys are never recorded to protect student privacy).
  Fields: timestamp, fieldId (which input field), keystrokeCount,
          pauseDurationMs (idle gap before this burst), typingSpeedWPM.

interactions.cursor
  Cursor position samples.
  Fields: timestamp, x, y (viewport pixels), pageUrl, elementTarget.

interactions.clipboard
  Copy, cut, and paste events.
  Fields: timestamp, action (copy | cut | paste),
          textLength (character count of copied/pasted text),
          sourceElement, pageUrl.
  Note: clipboard content is NOT recorded, only the length.

interactions.visibility
  Tab/window focus events — records when the student switches away.
  Fields: timestamp, visibleState (visible | hidden),
          hiddenDurationMs (how long the tab was hidden, on return),
          pageUrl.

interactions.viewport
  Browser window resize events.
  Fields: timestamp, width, height (pixels), orientation (portrait | landscape).

communications.chatbotMessages
  All messages in the floating Learning Assistant (chatbot) sidebar.
  Fields: createdAt, role (USER | ASSISTANT), content (message text),
          contextSource (what context was sent to the LLM),
          selectedText (slide or PDF text the student had selected),
          suggestedStrategy (learning strategy that triggered this message),
          promptTokens, completionTokens (LLM usage),
          model (LLM model name used).

communications.dialogueHistory
  Messages from the Dialogue RAG sidebar (document Q&A chat).
  Fields: role, text, timestamp, dialogueSessionId.

learning.interventionEvents
  Events triggered by the four learning strategies:
    Practice Testing       — generates quiz questions from slide content
    Interrogative Elaboration — asks "why/how" elaboration questions
    Stepwise Learning      — breaks content into step-by-step explanations
    Distributed Practice   — schedules spaced-repetition review prompts
  Fields: action (e.g. INTERVENTION_TRIGGERED, INTERVENTION_DISMISSED),
          timestamp, interventionId, metadata.

learning.assessmentEvents
  Quiz and knowledge-check activity events.
  Fields: action (e.g. QUESTION_ANSWERED, ASSESSMENT_COMPLETED),
          timestamp, assessmentId, attemptId, questionId, metadata.

learning.masteryTrajectory
  Knowledge component (KC) mastery score updates over time.
  Each entry represents a change in the student's estimated mastery of a
  specific knowledge component (topic/concept).
  Fields: timestamp, kcId, plus mastery-specific numeric fields from metadata.

learning.efDetections
  Executive Function (EF) constructs detected by text-mining chat messages.
  EF constructs include planning, working memory, cognitive flexibility, etc.
  Fields: createdAt, constructKey (EF category identifier),
          label (human-readable name), confidence (0.0–1.0),
          severity (low | medium | high), rationale (explanation text).

fullEventLog
  Complete chronological list of every activity log entry in the session.
  This is the raw event stream from which most other sections are derived.
  Useful for building custom timelines or filtering specific event types.
  Fields: id, action, occurredAt, courseId, moduleId, moduleItemId,
          assessmentId, attemptId, questionId, dialogueSessionId,
          interventionId, kcId, metadata.

replay.snapshots
  DOM snapshots of the student's browser, one per second (plus events).
  Each snapshot captures what was on screen at that exact moment.
  Fields: id, pageUrl, width, height (viewport size), scrollX, scrollY,
          capturedAt (Unix ms), trigger (periodic | route | initial | etc.),
          html (full serialised DOM — render in an iframe for replay),
          screenshotFile (path to corresponding JPEG in screen_recording/).
  Note: screenshotDataUrl has been extracted to screen_recording/frame_NNNN.jpg
  to keep this JSON file a manageable size.

recordings
  Metadata for each webcam video segment.
  Fields: index, filename (e.g. recording_0.webm), id, uploadStatus,
          startWallTime, endWallTime, durationMs, fileSizeBytes, mimeType,
          downloadUrl (presigned MinIO URL, valid for 1 hour from export time).
  Note: the actual video files are in the recordings/ folder.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TIMESTAMP ALIGNMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

All timestamps are ISO 8601 strings in UTC unless otherwise noted.
Exception: biometrics.emotionFrames.frameWallMs is Unix milliseconds (integer).

To get the offset from session start (in milliseconds):
  offset_ms = timestamp_ms - Date.parse(session.startedAt)

Aligning screen frames with webcam video:
  Each screen frame has a capturedAt value (Unix ms) in replay.snapshots.
  Each webcam recording segment has startWallTime and endWallTime.
  To find the webcam frame corresponding to a screen snapshot:
    webcam_offset_ms = snapshot.capturedAt - Date.parse(recording.startWallTime)
    webcam_frame     = webcam_offset_ms / 1000 * 15  (webcam is 15 fps)

Aligning screen frames with emotion data:
  emotionFrame.frameWallMs is directly comparable to snapshot.capturedAt
  (both are Unix milliseconds). Find the closest emotion frame to a snapshot:
    nearest = emotionFrames.reduce((a, b) =>
      Math.abs(a.frameWallMs - snapshot.capturedAt) <
      Math.abs(b.frameWallMs - snapshot.capturedAt) ? a : b)

Screen frame index to wall-clock time:
  Frame N (frame_NNNN.jpg) corresponds to replay.snapshots[N].capturedAt.
  To get the session offset: offset_ms = snapshot.capturedAt - Date.parse(session.startedAt)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
LOADING THE DATA — CODE EXAMPLES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Python — basic load:
  import json
  with open("session_data.json", encoding="utf-8") as f:
      data = json.load(f)

  print("Student:", data["student"]["name"])
  print("Duration:", data["session"]["durationSecs"], "seconds")
  print("Emotion frames:", len(data["biometrics"]["emotionFrames"]))
  print("Screen frames:", len([s for s in data["replay"]["snapshots"]
                                if s.get("screenshotFile")]))

Python — plot dominant emotion over time:
  import json, matplotlib.pyplot as plt
  from datetime import datetime

  with open("session_data.json", encoding="utf-8") as f:
      data = json.load(f)

  start_ms = datetime.fromisoformat(
      data["session"]["startedAt"].replace("Z", "+00:00")
  ).timestamp() * 1000

  frames = data["biometrics"]["emotionFrames"]
  times  = [(f["frameWallMs"] - start_ms) / 60000 for f in frames]  # minutes
  emotions = [f["dominantEmotion"] for f in frames]

  unique = list(set(emotions))
  for em in unique:
      ys = [1 if e == em else 0 for e in emotions]
      plt.plot(times, ys, label=em, alpha=0.7)
  plt.xlabel("Session time (minutes)")
  plt.legend()
  plt.show()

Python — overlay gaze on a screen frame:
  import json, base64
  from PIL import Image, ImageDraw
  from io import BytesIO

  with open("session_data.json", encoding="utf-8") as f:
      data = json.load(f)

  # Load frame 10 image
  frame_path = "screen_recording/frame_0010.jpg"
  img = Image.open(frame_path)
  draw = ImageDraw.Draw(img)

  snap = data["replay"]["snapshots"][10]
  snap_time = snap["capturedAt"]

  # Find gaze samples within ±500 ms of this snapshot
  for g in data["biometrics"]["gaze"]:
      from datetime import datetime
      t = datetime.fromisoformat(g["timestamp"].replace("Z", "+00:00")).timestamp() * 1000
      if abs(t - snap_time) < 500:
          draw.ellipse([g["gazeX"]-8, g["gazeY"]-8,
                        g["gazeX"]+8, g["gazeY"]+8],
                       outline="red", width=2)
  img.show()

JavaScript / Node.js — basic load:
  const fs   = require("fs");
  const data = JSON.parse(fs.readFileSync("session_data.json", "utf-8"));

  console.log("Student:", data.student.name);
  console.log("Clicks:", data.interactions.clicks.length);
  console.log("Chat messages:", data.communications.chatbotMessages.length);

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
QUESTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Contact the GALS development team for schema questions or data access issues.
`;

export async function exportSessionData(
  sessionId: string,
  onProgress?: (p: ExportProgress) => void,
): Promise<void> {
  const report = (stage: ExportProgress['stage'], percent: number, detail: string) =>
    onProgress?.({ stage, percent, detail });

  // ── Step 1: Fetch JSON from backend ──────────────────────────────────────
  report('fetching', 5, 'Fetching session data…');
  const token = localStorage.getItem('token');
  const headers: Record<string, string> = token ? { Authorization: `Bearer ${token}` } : {};

  const res = await fetch(`/api/activity-log/teacher/sessions/${sessionId}/export`, { headers });
  if (!res.ok) throw new Error(`Export fetch failed: ${res.status}`);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const sessionData: any = await res.json();
  report('fetching', 25, 'Session data received');

  // ── Step 2: Extract screenshots from snapshots ────────────────────────────
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const snapshots: any[] = sessionData?.replay?.snapshots ?? [];
  const screenshotFrames: { index: number; dataUrl: string; filename: string }[] = [];
  let frameIdx = 0;
  for (const snap of snapshots) {
    if (snap.screenshotDataUrl) {
      const filename = `frame_${String(frameIdx).padStart(4, '0')}.jpg`;
      screenshotFrames.push({
        index: frameIdx,
        dataUrl: snap.screenshotDataUrl as string,
        filename,
      });
      snap.screenshotFile = `screen_recording/${filename}`;
      delete snap.screenshotDataUrl;
      frameIdx++;
    }
  }
  report('fetching', 30, `Extracted ${screenshotFrames.length} screenshot frames`);

  // ── Step 3: Download webcam recording videos ──────────────────────────────
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const recordings: any[] = sessionData?.recordings ?? [];
  const videoBlobs: { filename: string; blob: Blob }[] = [];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const completedRecs = recordings.filter(
    (r: any) => r.uploadStatus === 'COMPLETED' && r.downloadUrl,
  );

  for (let i = 0; i < completedRecs.length; i++) {
    const rec = completedRecs[i];
    const pct = 30 + Math.round(((i + 1) / Math.max(completedRecs.length, 1)) * 20);
    report('downloading', pct, `Downloading webcam recording ${i + 1} of ${completedRecs.length}…`);
    try {
      const vRes = await fetch(rec.downloadUrl as string);
      if (vRes.ok) {
        const blob = await vRes.blob();
        videoBlobs.push({ filename: rec.filename as string, blob });
      }
    } catch (err) {
      console.error('[Export] webcam fetch error:', err);
    }
  }

  // ── Step 4: Build ZIP ────────────────────────────────────────────────────
  report('zipping', 84, 'Building ZIP archive…');
  const zip = new JSZip();

  const rawName: string = sessionData?._meta?.studentName ?? 'unknown';
  const rawCourse: string =
    sessionData?._meta?.courseName ?? sessionData?.session?.courseId ?? 'unknown_course';
  const startedAt: string = sessionData?._meta?.sessionStartedAt ?? new Date().toISOString();
  const dt = new Date(startedAt);
  const datePart = dt.toISOString().slice(0, 10);
  const timePart = dt.toISOString().slice(11, 19).replace(/:/g, '-');
  const safeName = (s: string) =>
    s
      .replace(/[^a-zA-Z0-9]/g, '_')
      .replace(/_+/g, '_')
      .replace(/^_|_$/g, '');
  const folderName = `${safeName(rawName)}_${safeName(rawCourse)}_${datePart}_${timePart}`;

  const folder = zip.folder(folderName)!;

  folder.file('README.txt', README);
  folder.file('session_data.json', JSON.stringify(sessionData, null, 2));

  // Webcam recordings
  if (videoBlobs.length > 0) {
    const recFolder = folder.folder('recordings')!;
    for (const { filename, blob } of videoBlobs) {
      recFolder.file(filename, blob);
    }
  }

  // Screen recording frames
  if (screenshotFrames.length > 0) {
    const screenFolder = folder.folder('screen_recording')!;
    for (const { dataUrl, filename } of screenshotFrames) {
      const base64 = (dataUrl as string).replace(/^data:[^;]+;base64,/, '');
      screenFolder.file(filename, base64, { base64: true });
    }
  }

  // DOM snapshots — fetched via paginated endpoint to avoid OOM on long sessions
  const snapshotCount: number = sessionData?.replay?.snapshotCount ?? 0;
  if (snapshotCount > 0) {
    report('zipping', 86, `Fetching ${snapshotCount} DOM snapshots…`);
    const domFolder = folder.folder('dom_snapshots')!;
    const DOM_LIMIT = 20;
    let domOffset = 0;
    let domTotal = snapshotCount;
    while (domOffset < domTotal) {
      const domRes = await fetch(
        `/api/activity-log/teacher/sessions/${sessionId}/export/dom-snapshots?offset=${domOffset}&limit=${DOM_LIMIT}`,
        { headers },
      );
      if (!domRes.ok) throw new Error(`DOM snapshot fetch failed: ${domRes.status}`);
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { total, snapshots: batch }: { total: number; snapshots: any[] } = await domRes.json();
      domTotal = total;
      for (const snap of batch) {
        if (snap.html) {
          const filename = (snap.htmlFile as string).replace('dom_snapshots/', '');
          domFolder.file(filename, snap.html as string);
        }
      }
      domOffset += DOM_LIMIT;
      const pct = 86 + Math.min(7, Math.round((domOffset / domTotal) * 7));
      report(
        'zipping',
        pct,
        `Saving DOM snapshots ${Math.min(domOffset, domTotal)} of ${domTotal}…`,
      );
    }
  }

  report('zipping', 94, 'Compressing…');
  const zipBlob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 1 },
  });

  // ── Step 6: Trigger download ──────────────────────────────────────────────
  report('done', 100, 'Done');
  const url = URL.createObjectURL(zipBlob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${folderName}.zip`;
  a.click();
  URL.revokeObjectURL(url);
}
