-- Stage 03 of the RAG upgrade (prompts_rag/03_contextual_retrieval.md).
--
-- Adds `contextual_text` to per-chunk tables on BOTH corpora so we can
-- store the 50-100 token document-aware blurb generated by the
-- contextualizer at ingest time. The blurb is:
--   - PREPENDED to the chunk text before embedding (so the vector
--     captures the chunk's place in the doc, not just its raw content),
--   - PREPENDED to the chunk text in the lexical (ILIKE/BM25-ish) scan
--     so keyword search benefits from the added context as well, and
--   - NEVER shown to the generator — citations still quote the
--     original `content` / `text` column.
--
-- This is the Anthropic "Contextual Retrieval" pattern. Empirically
-- reduces retrieval failure rate by ~35% (embeddings only) and ~49%
-- when both embeddings AND BM25 are contextualised.
--
-- Both columns are nullable with no default so:
--   (a) existing rows continue to validate without a backfill, and
--   (b) the retriever uses `COALESCE(contextual_text, '')` to fall
--       through to bare-text behaviour for un-backfilled rows — same
--       behaviour as Stage 02.
--
-- Idempotent: `ADD COLUMN IF NOT EXISTS` is supported on PG ≥ 9.6.

ALTER TABLE "document_chunks"
  ADD COLUMN IF NOT EXISTS "contextual_text" TEXT;

ALTER TABLE "student_rag_chunks"
  ADD COLUMN IF NOT EXISTS "contextual_text" TEXT;
