export enum ActivityAction {
  SESSION_START = 'SESSION_START',
  SESSION_END = 'SESSION_END',
  SESSION_HEARTBEAT = 'SESSION_HEARTBEAT',

  MODULE_OPENED = 'MODULE_OPENED',
  MODULE_ITEM_VIEWED = 'MODULE_ITEM_VIEWED',
  KC_GRAPH_VIEWED = 'KC_GRAPH_VIEWED',

  ASSESSMENT_STARTED = 'ASSESSMENT_STARTED',
  QUESTION_VIEWED = 'QUESTION_VIEWED',
  QUESTION_ANSWERED = 'QUESTION_ANSWERED',
  ASSESSMENT_SUBMITTED = 'ASSESSMENT_SUBMITTED',
  ASSESSMENT_GRADED = 'ASSESSMENT_GRADED',

  DIALOGUE_SESSION_STARTED = 'DIALOGUE_SESSION_STARTED',
  DIALOGUE_MESSAGE_SENT = 'DIALOGUE_MESSAGE_SENT',
  DIALOGUE_MESSAGE_RECEIVED = 'DIALOGUE_MESSAGE_RECEIVED',
  DIALOGUE_SESSION_ENDED = 'DIALOGUE_SESSION_ENDED',
  CHATBOT_MESSAGE_SENT = 'CHATBOT_MESSAGE_SENT',
  CHATBOT_MESSAGE_RECEIVED = 'CHATBOT_MESSAGE_RECEIVED',

  INTERVENTION_TRIGGERED = 'INTERVENTION_TRIGGERED',
  INTERVENTION_VIEWED = 'INTERVENTION_VIEWED',
  INTERVENTION_COMPLETED = 'INTERVENTION_COMPLETED',
  INTERVENTION_DISMISSED = 'INTERVENTION_DISMISSED',
  // Practice testing — student configured count + coverage before generation
  PRACTICE_TEST_CONFIGURED = 'PRACTICE_TEST_CONFIGURED',

  SPACED_REP_CARD_VIEWED = 'SPACED_REP_CARD_VIEWED',
  SPACED_REP_CARD_RATED = 'SPACED_REP_CARD_RATED',

  STUDY_MATERIAL_UPLOADED = 'STUDY_MATERIAL_UPLOADED',
  STUDY_GUIDE_GENERATED = 'STUDY_GUIDE_GENERATED',
  STUDIO_OUTPUT_REQUESTED = 'STUDIO_OUTPUT_REQUESTED',
  STUDIO_OUTPUT_VIEWED = 'STUDIO_OUTPUT_VIEWED',

  MASTERY_UPDATED = 'MASTERY_UPDATED',
  FEEDBACK_RECEIVED = 'FEEDBACK_RECEIVED',

  // Recording (Feature 04)
  RECORDING_STARTED = 'RECORDING_STARTED',
  RECORDING_STOPPED = 'RECORDING_STOPPED',
  RECORDING_SEGMENT_UPLOADED = 'RECORDING_SEGMENT_UPLOADED',
  RECORDING_UPLOAD_FAILED = 'RECORDING_UPLOAD_FAILED',
  RECORDING_RESUMED = 'RECORDING_RESUMED',

  // Pupil Size (Feature 01)
  PUPIL_SIZE_TRACKING_STARTED = 'PUPIL_SIZE_TRACKING_STARTED',
  PUPIL_SIZE_TRACKING_STOPPED = 'PUPIL_SIZE_TRACKING_STOPPED',
  PUPIL_SIZE_BATCH_SUBMITTED = 'PUPIL_SIZE_BATCH_SUBMITTED',

  // WebGazer (Feature 02)
  WEBGAZER_TRACKING_STARTED = 'WEBGAZER_TRACKING_STARTED',
  WEBGAZER_TRACKING_STOPPED = 'WEBGAZER_TRACKING_STOPPED',
  WEBGAZER_CALIBRATION_STARTED = 'WEBGAZER_CALIBRATION_STARTED',
  WEBGAZER_CALIBRATION_COMPLETED = 'WEBGAZER_CALIBRATION_COMPLETED',
  WEBGAZER_CALIBRATION_SKIPPED = 'WEBGAZER_CALIBRATION_SKIPPED',
  WEBGAZER_BATCH_SUBMITTED = 'WEBGAZER_BATCH_SUBMITTED',
  WEBGAZER_RECALIBRATION_PROMPTED = 'WEBGAZER_RECALIBRATION_PROMPTED',

  // py-feat (Feature 03)
  PYFEAT_JOB_ENQUEUED = 'PYFEAT_JOB_ENQUEUED',
  PYFEAT_JOB_COMPLETED = 'PYFEAT_JOB_COMPLETED',
  PYFEAT_JOB_FAILED = 'PYFEAT_JOB_FAILED',

  // Self-report emotion survey (shown every 15 minutes)
  EMOTION_SELF_REPORT = 'EMOTION_SELF_REPORT',

  // Code Decomposition (DBox) — node-level events INTERVENTION_* doesn't
  // carry enough detail for (which node, which hint tier)
  CODE_DECOMP_TREE_CHECKED = 'CODE_DECOMP_TREE_CHECKED',
  CODE_DECOMP_NODE_HINT_VIEWED = 'CODE_DECOMP_NODE_HINT_VIEWED',
  CODE_DECOMP_NODE_REVEALED = 'CODE_DECOMP_NODE_REVEALED',
  CODE_DECOMP_STAGE_ADVANCED = 'CODE_DECOMP_STAGE_ADVANCED',
  CODE_DECOMP_MATCH_CHECKED = 'CODE_DECOMP_MATCH_CHECKED',
}
