export enum ActivityAction {
  SESSION_START = 'SESSION_START',
  SESSION_END = 'SESSION_END',
  SESSION_HEARTBEAT = 'SESSION_HEARTBEAT',

  MODULE_OPENED = 'MODULE_OPENED',
  MODULE_ITEM_VIEWED = 'MODULE_ITEM_VIEWED',
  KC_GRAPH_VIEWED = 'KC_GRAPH_VIEWED',

  ASSESSMENT_STARTED = 'ASSESSMENT_STARTED',
  QUESTION_VIEWED = 'QUESTION_VIEWED',
  QUESTION_ANSWERED = 'QUESTION_ANSWERED',
  ASSESSMENT_SUBMITTED = 'ASSESSMENT_SUBMITTED',
  ASSESSMENT_GRADED = 'ASSESSMENT_GRADED',

  DIALOGUE_SESSION_STARTED = 'DIALOGUE_SESSION_STARTED',
  DIALOGUE_MESSAGE_SENT = 'DIALOGUE_MESSAGE_SENT',
  DIALOGUE_MESSAGE_RECEIVED = 'DIALOGUE_MESSAGE_RECEIVED',
  DIALOGUE_SESSION_ENDED = 'DIALOGUE_SESSION_ENDED',

  INTERVENTION_TRIGGERED = 'INTERVENTION_TRIGGERED',
  INTERVENTION_VIEWED = 'INTERVENTION_VIEWED',
  INTERVENTION_COMPLETED = 'INTERVENTION_COMPLETED',
  INTERVENTION_DISMISSED = 'INTERVENTION_DISMISSED',

  SPACED_REP_CARD_VIEWED = 'SPACED_REP_CARD_VIEWED',
  SPACED_REP_CARD_RATED = 'SPACED_REP_CARD_RATED',

  STUDY_MATERIAL_UPLOADED = 'STUDY_MATERIAL_UPLOADED',
  STUDY_GUIDE_GENERATED = 'STUDY_GUIDE_GENERATED',
  STUDIO_OUTPUT_REQUESTED = 'STUDIO_OUTPUT_REQUESTED',
  STUDIO_OUTPUT_VIEWED = 'STUDIO_OUTPUT_VIEWED',

  MASTERY_UPDATED = 'MASTERY_UPDATED',
  FEEDBACK_RECEIVED = 'FEEDBACK_RECEIVED',
}
