export enum ActivityAction {
  SESSION_START = 'SESSION_START',
  SESSION_END = 'SESSION_END',
  SESSION_HEARTBEAT = 'SESSION_HEARTBEAT',

  MODULE_OPENED = 'MODULE_OPENED',
  MODULE_ITEM_VIEWED = 'MODULE_ITEM_VIEWED',

  ASSESSMENT_STARTED = 'ASSESSMENT_STARTED',
  QUESTION_VIEWED = 'QUESTION_VIEWED',
  QUESTION_ANSWERED = 'QUESTION_ANSWERED',
  ASSESSMENT_SUBMITTED = 'ASSESSMENT_SUBMITTED',
  ASSESSMENT_GRADED = 'ASSESSMENT_GRADED',

  DIALOGUE_SESSION_STARTED = 'DIALOGUE_SESSION_STARTED',
  DIALOGUE_MESSAGE_SENT = 'DIALOGUE_MESSAGE_SENT',
  DIALOGUE_MESSAGE_RECEIVED = 'DIALOGUE_MESSAGE_RECEIVED',
  DIALOGUE_SESSION_ENDED = 'DIALOGUE_SESSION_ENDED',
  CHATBOT_MESSAGE_SENT = 'CHATBOT_MESSAGE_SENT',
  CHATBOT_MESSAGE_RECEIVED = 'CHATBOT_MESSAGE_RECEIVED',

  INTERVENTION_TRIGGERED = 'INTERVENTION_TRIGGERED',
  INTERVENTION_VIEWED = 'INTERVENTION_VIEWED',
  INTERVENTION_COMPLETED = 'INTERVENTION_COMPLETED',
  INTERVENTION_DISMISSED = 'INTERVENTION_DISMISSED',
  // Practice testing — student configured count + coverage before generation
  PRACTICE_TEST_CONFIGURED = 'PRACTICE_TEST_CONFIGURED',

  SPACED_REP_CARD_VIEWED = 'SPACED_REP_CARD_VIEWED',
  SPACED_REP_CARD_RATED = 'SPACED_REP_CARD_RATED',

  STUDY_MATERIAL_UPLOADED = 'STUDY_MATERIAL_UPLOADED',
  STUDY_GUIDE_GENERATED = 'STUDY_GUIDE_GENERATED',
  STUDIO_OUTPUT_REQUESTED = 'STUDIO_OUTPUT_REQUESTED',
  STUDIO_OUTPUT_VIEWED = 'STUDIO_OUTPUT_VIEWED',

  FEEDBACK_RECEIVED = 'FEEDBACK_RECEIVED',

  // Recording (Feature 04)
  RECORDING_STARTED = 'RECORDING_STARTED',
  RECORDING_STOPPED = 'RECORDING_STOPPED',
  RECORDING_SEGMENT_UPLOADED = 'RECORDING_SEGMENT_UPLOADED',
  RECORDING_UPLOAD_FAILED = 'RECORDING_UPLOAD_FAILED',
  RECORDING_RESUMED = 'RECORDING_RESUMED',

  // Pupil Size (Feature 01)
  PUPIL_SIZE_TRACKING_STARTED = 'PUPIL_SIZE_TRACKING_STARTED',
  PUPIL_SIZE_TRACKING_STOPPED = 'PUPIL_SIZE_TRACKING_STOPPED',
  PUPIL_SIZE_BATCH_SUBMITTED = 'PUPIL_SIZE_BATCH_SUBMITTED',

  // WebGazer (Feature 02)
  WEBGAZER_TRACKING_STARTED = 'WEBGAZER_TRACKING_STARTED',
  WEBGAZER_TRACKING_STOPPED = 'WEBGAZER_TRACKING_STOPPED',
  WEBGAZER_CALIBRATION_STARTED = 'WEBGAZER_CALIBRATION_STARTED',
  WEBGAZER_CALIBRATION_COMPLETED = 'WEBGAZER_CALIBRATION_COMPLETED',
  WEBGAZER_CALIBRATION_SKIPPED = 'WEBGAZER_CALIBRATION_SKIPPED',
  WEBGAZER_BATCH_SUBMITTED = 'WEBGAZER_BATCH_SUBMITTED',
  WEBGAZER_RECALIBRATION_PROMPTED = 'WEBGAZER_RECALIBRATION_PROMPTED',

  // py-feat (Feature 03)
  PYFEAT_JOB_ENQUEUED = 'PYFEAT_JOB_ENQUEUED',
  PYFEAT_JOB_COMPLETED = 'PYFEAT_JOB_COMPLETED',
  PYFEAT_JOB_FAILED = 'PYFEAT_JOB_FAILED',

  // Self-report emotion survey (shown every 15 minutes)
  EMOTION_SELF_REPORT = 'EMOTION_SELF_REPORT',

  // Code Decomposition (DBox) — node-level events INTERVENTION_* doesn't
  // carry enough detail for (which node, which hint tier)
  CODE_DECOMP_TREE_CHECKED = 'CODE_DECOMP_TREE_CHECKED',
  CODE_DECOMP_NODE_HINT_VIEWED = 'CODE_DECOMP_NODE_HINT_VIEWED',
  CODE_DECOMP_NODE_REVEALED = 'CODE_DECOMP_NODE_REVEALED',
  CODE_DECOMP_STAGE_ADVANCED = 'CODE_DECOMP_STAGE_ADVANCED',
  CODE_DECOMP_MATCH_CHECKED = 'CODE_DECOMP_MATCH_CHECKED',

  // Interactive lessons — prompting course (Process Mining Library v2;
  // docs/process-mining/PHASE0_DISCOVERY.md §9)
  SLIDE_ENTERED = 'SLIDE_ENTERED',
  SLIDE_EXITED = 'SLIDE_EXITED',
  ATTEMPT_STARTED = 'ATTEMPT_STARTED',
  PREDICTION_COMMITTED = 'PREDICTION_COMMITTED',
  REFERENCE_REVEALED = 'REFERENCE_REVEALED',
  GAP_NOTED = 'GAP_NOTED',
  BELIEF_COMMITTED = 'BELIEF_COMMITTED',
  BELIEF_REVISED = 'BELIEF_REVISED',
  MCQ_ANSWERED = 'MCQ_ANSWERED',
  RATIONALE_SUBMITTED = 'RATIONALE_SUBMITTED',
  SELF_CHECK_SUBMITTED = 'SELF_CHECK_SUBMITTED',
  RESULTS_RECORDED = 'RESULTS_RECORDED',
  CRITERION_SELF_SCORED = 'CRITERION_SELF_SCORED',
  REFLECTION_SUBMITTED = 'REFLECTION_SUBMITTED',
  CONFIDENCE_RATED = 'CONFIDENCE_RATED',
  IDLE_STARTED = 'IDLE_STARTED',
  IDLE_ENDED = 'IDLE_ENDED',

  // Prompt Lab — AI-interaction layer (prompting course, Phase 3)
  RUN_SETTINGS_RECORDED = 'RUN_SETTINGS_RECORDED',
  PROMPT_GOAL_DECLARED = 'PROMPT_GOAL_DECLARED',
  PROMPT_SUBMITTED = 'PROMPT_SUBMITTED',
  OUTPUT_REGENERATED = 'OUTPUT_REGENERATED',
  AI_OUTPUT_VIEWED = 'AI_OUTPUT_VIEWED',
  PROMPT_VERSION_SAVED = 'PROMPT_VERSION_SAVED',
  PROMPT_REVISION_TAGGED = 'PROMPT_REVISION_TAGGED',
  TOKEN_COUNT_CHECKED = 'TOKEN_COUNT_CHECKED',
  TEST_CASE_RUN = 'TEST_CASE_RUN',
  TEST_RESULT_RECORDED = 'TEST_RESULT_RECORDED',
  OUTPUT_RATED = 'OUTPUT_RATED',
  OUTPUT_VERIFIED = 'OUTPUT_VERIFIED',
  OUTPUT_COPIED = 'OUTPUT_COPIED',
  OUTPUT_PASTED = 'OUTPUT_PASTED',
  OUTPUT_EDITED = 'OUTPUT_EDITED',

  // Transfer task (prompting course, Phase 5)
  TRANSFER_TASK_SUBMITTED = 'TRANSFER_TASK_SUBMITTED',
}
